// GENERATED by @ethonline26/mcpgen. Do not edit: regenerate from the receipt, the proto and views.sql.
// MCP server for Substreams package erc4626-flows v0.1.0 (output module map_events).
// Transport: stdio. Configuration by environment:
//   CLICKHOUSE_URL        http(s)://host:port  (user:password@ and ?database= in the URL are honoured; default http://localhost:8123)
//   CLICKHOUSE_USER / CLICKHOUSE_PASSWORD / CLICKHOUSE_DATABASE
//   BASE_RPC_URL          JSON-RPC endpoint for the receipt's chain (eth_blockNumber / eth_chainId); required for the lag check
//   MAX_LAG_BLOCKS        refuse when chain head - sink head exceeds this (default 300)
//   CHECK_INTERVAL_SECONDS  fail-closed re-check period (default 60)
//   RECEIPT_PATH          Deployment Receipt to re-read every cycle (default ./receipt.json next to manifest.json)
//   CLICKHOUSE_READONLY   1 (default) or 2; see runtime/clickhouse.ts
import { readFile, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { HttpClickHouseClient } from "./runtime/clickhouse.ts";
import { Guardian } from "./runtime/guardian.ts";
import { JsonRpcChainHead } from "./runtime/rpc.ts";
import { registerTools } from "./runtime/tools.ts";
import type { Manifest, RuntimeReceipt } from "./runtime/types.ts";
import { inputShapes } from "./tools.generated.ts";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const log = (m: string): void => { process.stderr.write(`[@ethonline26/mcp-vaultflows] ${m}\n`); };

const manifest = JSON.parse(readFileSync(join(pkgRoot, "manifest.json"), "utf8")) as Manifest;
const receiptPath = process.env.RECEIPT_PATH ?? join(pkgRoot, "receipt.json");
const readReceipt = (): Promise<RuntimeReceipt> =>
  new Promise((ok, fail) => readFile(receiptPath, "utf8", (err, text) => (err ? fail(err) : ok(JSON.parse(text) as RuntimeReceipt))));
const receiptAtStart = JSON.parse(readFileSync(receiptPath, "utf8")) as RuntimeReceipt;

const chUrl = new URL(process.env.CLICKHOUSE_URL ?? "http://localhost:8123");
const receiptSink = (receiptAtStart as { sink?: { database?: string } }).sink;
const database = process.env.CLICKHOUSE_DATABASE ?? chUrl.searchParams.get("database") ?? receiptSink?.database ?? "default";
const user = process.env.CLICKHOUSE_USER ?? (chUrl.username ? decodeURIComponent(chUrl.username) : undefined);
const password = process.env.CLICKHOUSE_PASSWORD ?? (chUrl.password ? decodeURIComponent(chUrl.password) : undefined);
const readonlyEnv = process.env.CLICKHOUSE_READONLY;
const clickhouse = new HttpClickHouseClient({
  url: `${chUrl.protocol}//${chUrl.host}`,
  ...(user !== undefined ? { user } : {}),
  ...(password !== undefined ? { password } : {}),
  database,
  timeoutMs: manifest.policy.queryTimeoutMs,
  readonly: readonlyEnv === "2" ? 2 : 1,
});

const rpcUrl = process.env.BASE_RPC_URL;
if (!rpcUrl) log("BASE_RPC_URL is not set: the lag check cannot run, so every data tool will refuse with check_unavailable");
const chainHead = rpcUrl
  ? new JsonRpcChainHead(rpcUrl, manifest.policy.queryTimeoutMs)
  : { head: async (): Promise<{ blockNumber: number; chainId: number }> => { throw new Error("BASE_RPC_URL not set"); } };

const maxLagBlocks = Number(process.env.MAX_LAG_BLOCKS ?? manifest.policy.maxLagBlocksDefault);
const checkIntervalMs = Number(process.env.CHECK_INTERVAL_SECONDS ?? manifest.policy.checkIntervalSeconds) * 1000;

const guardian = new Guardian({ manifest, readReceipt, clickhouse, chainHead, database, maxLagBlocks, checkIntervalMs, log });
const server = new McpServer({ name: "@ethonline26/mcp-vaultflows", version: "0.1.0" });
registerTools(server, { guardian, clickhouse, log }, inputShapes);

const transport = new StdioServerTransport();
await server.connect(transport);
log(`connected; ${manifest.tools.length} tools; package ${manifest.package.name} ${manifest.package.version} (${manifest.package.deploymentMode}); database ${database}; maxLagBlocks ${maxLagBlocks}`);
void guardian.start();
process.on("SIGINT", () => { guardian.stop(); process.exit(0); });
process.on("SIGTERM", () => { guardian.stop(); process.exit(0); });
