// @generated
// This file is @generated by prost-build.
/// Output of the single sink module. Each repeated field maps to one ClickHouse table.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub vault_flows: ::prost::alloc::vec::Vec<VaultFlow>,
    #[prost(message, repeated, tag="2")]
    pub share_value_observations: ::prost::alloc::vec::Vec<ShareValueObservation>,
    #[prost(message, repeated, tag="3")]
    pub vaults: ::prost::alloc::vec::Vec<VaultMeta>,
    #[prost(message, repeated, tag="4")]
    pub share_transfers: ::prost::alloc::vec::Vec<ShareTransfer>,
}
/// One Deposit or Withdraw log on a vault in the configured vault list.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFlow {
    /// "{chain_id}-{block_number}-{log_index}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub chain_id: u32,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// unix seconds
    #[prost(uint64, tag="5")]
    pub block_timestamp: u64,
    #[prost(string, tag="6")]
    pub tx_hash: ::prost::alloc::string::String,
    /// receipt log index within the block (block-wide, not per-transaction)
    #[prost(uint32, tag="7")]
    pub log_index: u32,
    #[prost(string, tag="8")]
    pub vault: ::prost::alloc::string::String,
    /// event `sender`: the address that called deposit/mint/withdraw/redeem
    #[prost(string, tag="9")]
    pub caller: ::prost::alloc::string::String,
    /// whose shares were minted (deposit) or burned (withdraw)
    #[prost(string, tag="10")]
    pub owner: ::prost::alloc::string::String,
    /// who received assets on withdraw; equals owner on deposit
    #[prost(string, tag="11")]
    pub receiver: ::prost::alloc::string::String,
    /// Values exactly `deposit` (ERC-4626 Deposit(sender, owner, assets, shares)) or `withdraw`
    /// (ERC-4626 Withdraw(sender, receiver, owner, assets, shares)). Lowercase, never empty.
    #[prost(string, tag="12")]
    pub direction: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub assets_raw: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub shares_raw: ::prost::alloc::string::String,
    /// assets_raw / 10^asset_decimals; "0" when meta_valid is false
    #[prost(string, tag="15")]
    pub assets_normalized: ::prost::alloc::string::String,
    /// shares_raw / 10^share_decimals; "0" when meta_valid is false
    #[prost(string, tag="16")]
    pub shares_normalized: ::prost::alloc::string::String,
    /// 0 when meta_valid is false
    #[prost(uint32, tag="17")]
    pub asset_decimals: u32,
    /// 0 when meta_valid is false
    #[prost(uint32, tag="18")]
    pub share_decimals: u32,
    /// assets_normalized / shares_normalized for this single flow, in asset units per whole share. Deposit-implied
    /// when direction is `deposit` (per EIP-4626 the Deposit `assets` includes any entry fee); withdraw-implied when
    /// `withdraw` (Withdraw `assets` is net of exit fee). "0" when shares_raw is zero or meta_valid is false.
    #[prost(string, tag="19")]
    pub execution_rate: ::prost::alloc::string::String,
    /// true when the vault passed the first-sight metadata probe (asset(), decimals(), asset.decimals(),
    /// totalAssets(), convertToAssets()) and the normalized fields are populated.
    #[prost(bool, tag="20")]
    pub meta_valid: bool,
    /// status of the metadata probe this row relied on: true when every call returned and decoded
    #[prost(bool, tag="22")]
    pub call_ok: bool,
    /// empty when call_ok; otherwise a short reason, e.g. "convertToAssets: reverted"
    #[prost(string, tag="23")]
    pub call_error: ::prost::alloc::string::String,
}
/// Point-in-time read of a vault at a sampled block (block_number % sample_interval_blocks == 0).
/// One row per configured vault per sampled block, emitted even when the calls fail (call_ok = false).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShareValueObservation {
    /// "{chain_id}-{block_number}-{vault}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub chain_id: u32,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// unix seconds
    #[prost(uint64, tag="5")]
    pub block_timestamp: u64,
    #[prost(string, tag="6")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint32, tag="7")]
    pub sample_interval_blocks: u32,
    /// convertToAssets(10^share_decimals) executed at this block's state. "0" when call_ok is false.
    #[prost(string, tag="8")]
    pub assets_per_share_raw: ::prost::alloc::string::String,
    /// assets_per_share_raw / 10^asset_decimals (assets per one whole share). "0" when call_ok is false.
    #[prost(string, tag="9")]
    pub assets_per_share_normalized: ::prost::alloc::string::String,
    /// totalAssets(); "0" when call_ok is false
    #[prost(string, tag="10")]
    pub total_assets_raw: ::prost::alloc::string::String,
    /// totalSupply(); "0" when call_ok is false
    #[prost(string, tag="11")]
    pub total_supply_raw: ::prost::alloc::string::String,
    /// true only if convertToAssets, totalAssets and totalSupply all returned and decoded
    #[prost(bool, tag="13")]
    pub call_ok: bool,
    /// empty when call_ok; otherwise a short reason naming the failed call
    #[prost(string, tag="14")]
    pub call_error: ::prost::alloc::string::String,
}
/// First-sight metadata of every address that emitted a matching Deposit/Withdraw. One row per vault
/// per chain, written when the probe first runs. Non-compliant addresses are recorded with compliant=false
/// and never produce VaultFlow rows.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultMeta {
    /// "{chain_id}-{vault}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub chain_id: u32,
    #[prost(string, tag="3")]
    pub vault: ::prost::alloc::string::String,
    /// block at which the probe ran
    #[prost(uint64, tag="4")]
    pub first_seen_block: u64,
    /// asset() result; empty if the probe failed (plain string column, empty is allowed)
    #[prost(string, tag="5")]
    pub asset: ::prost::alloc::string::String,
    /// 0 if the probe failed
    #[prost(uint32, tag="6")]
    pub asset_decimals: u32,
    /// 0 if the probe failed
    #[prost(uint32, tag="7")]
    pub share_decimals: u32,
    /// name() if decodable, else empty
    #[prost(string, tag="8")]
    pub name: ::prost::alloc::string::String,
    /// symbol() if decodable, else empty
    #[prost(string, tag="9")]
    pub symbol: ::prost::alloc::string::String,
    /// heuristic: all probe calls succeeded and decoded
    #[prost(bool, tag="10")]
    pub compliant: bool,
    /// true when the address is in the package's vault parameter
    #[prost(bool, tag="11")]
    pub in_configured_list: bool,
    /// true when every probe call returned and decoded (equals compliant in v0.1.0)
    #[prost(bool, tag="13")]
    pub call_ok: bool,
    /// empty when call_ok; otherwise the first failed call, e.g. "asset: reverted"
    #[prost(string, tag="14")]
    pub call_error: ::prost::alloc::string::String,
}
/// ERC-20 Transfer of vault shares between two owners (share migration), excluding the mint on
/// Deposit (from = 0x0) and the burn on Withdraw (to = 0x0). Optional table; may be empty in v0.1.0.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShareTransfer {
    /// "{chain_id}-{block_number}-{log_index}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub chain_id: u32,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub block_timestamp: u64,
    #[prost(string, tag="6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="7")]
    pub log_index: u32,
    #[prost(string, tag="8")]
    pub vault: ::prost::alloc::string::String,
    /// Transfer `from` (renamed: bare `to` is a ClickHouse keyword and the sink emits unquoted identifiers)
    #[prost(string, tag="9")]
    pub from_owner: ::prost::alloc::string::String,
    /// Transfer `to`
    #[prost(string, tag="10")]
    pub to_owner: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub shares_raw: ::prost::alloc::string::String,
    /// "0" when meta_valid is false
    #[prost(string, tag="12")]
    pub shares_normalized: ::prost::alloc::string::String,
    #[prost(uint32, tag="13")]
    pub share_decimals: u32,
    #[prost(bool, tag="14")]
    pub meta_valid: bool,
}
// @@protoc_insertion_point(module)
