// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EstimateRequest {
    #[prost(message, optional, tag="1")]
    pub package: ::core::option::Option<super::super::v1::Package>,
    #[prost(string, tag="2")]
    pub output_module: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub start_block_num: i64,
    #[prost(uint64, tag="4")]
    pub stop_block_num: u64,
    #[prost(double, tag="5")]
    pub sample_percentage: f64,
    #[prost(map="string, string", tag="6")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag="7")]
    pub network: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EstimateResponse {
    #[prost(oneof="estimate_response::Message", tags="1, 2")]
    pub message: ::core::option::Option<estimate_response::Message>,
}
/// Nested message and enum types in `EstimateResponse`.
pub mod estimate_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Progress(super::EstimateProgress),
        #[prost(message, tag="2")]
        Estimate(super::Estimate),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EstimateProgress {
    #[prost(uint64, tag="1")]
    pub completed_segments: u64,
    #[prost(uint64, tag="2")]
    pub total_segments: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Estimate {
    #[prost(uint64, tag="1")]
    pub resolved_start_block: u64,
    #[prost(uint64, tag="2")]
    pub resolved_stop_block: u64,
    #[prost(uint64, tag="3")]
    pub segment_block_count: u64,
    #[prost(uint32, tag="4")]
    pub stage_count: u32,
    #[prost(uint64, tag="5")]
    pub blocks_to_process: u64,
    #[prost(uint64, tag="7")]
    pub total_blocks_to_process_uncached: u64,
    #[prost(uint64, tag="8")]
    pub estimated_egress_bytes: u64,
    #[prost(double, tag="9")]
    pub bytes_per_block: f64,
    #[prost(message, optional, tag="10")]
    pub sampling: ::core::option::Option<Sampling>,
    #[prost(uint64, tag="11")]
    pub framing_bytes_per_message: u64,
    #[prost(uint64, tag="12")]
    pub estimated_message_count: u64,
    #[prost(bool, tag="13")]
    pub block_filtered: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sampling {
    #[prost(double, tag="1")]
    pub percentage: f64,
    #[prost(string, tag="3")]
    pub note: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub sampled_blocks: u64,
    #[prost(uint64, tag="5")]
    pub sampled_bytes: u64,
    #[prost(message, repeated, tag="6")]
    pub segments: ::prost::alloc::vec::Vec<SampledSegment>,
    #[prost(uint64, tag="7")]
    pub sampled_messages: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SampledSegment {
    #[prost(uint64, tag="1")]
    pub start_block: u64,
    #[prost(uint64, tag="2")]
    pub stop_block: u64,
    #[prost(uint64, tag="3")]
    pub uncompressed_bytes: u64,
    #[prost(bool, tag="4")]
    pub from_cache: bool,
    #[prost(bool, tag="5")]
    pub size_from_metadata: bool,
    #[prost(uint64, tag="6")]
    pub represented_start_block: u64,
    #[prost(uint64, tag="7")]
    pub represented_blocks: u64,
    #[prost(uint64, tag="8")]
    pub estimated_bytes: u64,
    #[prost(uint64, tag="9")]
    pub message_count: u64,
    #[prost(uint64, tag="10")]
    pub processed_blocks: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(oneof="response::Message", tags="1, 2, 3, 4, 5, 10, 11")]
    pub message: ::core::option::Option<response::Message>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Session(super::super::v2::SessionInit),
        #[prost(message, tag="2")]
        Progress(super::super::v2::ModulesProgress),
        #[prost(message, tag="3")]
        BlockScopedDatas(super::BlockScopedDatas),
        #[prost(message, tag="4")]
        BlockUndoSignal(super::super::v2::BlockUndoSignal),
        #[prost(message, tag="5")]
        FatalError(super::super::v2::Error),
        #[prost(message, tag="10")]
        DebugSnapshotData(super::super::v2::InitialSnapshotData),
        #[prost(message, tag="11")]
        DebugSnapshotComplete(super::super::v2::InitialSnapshotComplete),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockScopedDatas {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<super::v2::BlockScopedData>,
}
// @@protoc_insertion_point(module)
