// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(int64, tag="1")]
    pub start_block_num: i64,
    #[prost(string, tag="2")]
    pub start_cursor: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub stop_block_num: u64,
    #[prost(bool, tag="4")]
    pub final_blocks_only: bool,
    #[prost(bool, tag="5")]
    pub production_mode: bool,
    #[prost(string, tag="6")]
    pub output_module: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub package: ::core::option::Option<super::super::v1::Package>,
    #[prost(map="string, string", tag="8")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag="9")]
    pub network: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="10")]
    pub debug_initial_store_snapshot_for_modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="11")]
    pub noop_mode: bool,
    #[prost(uint64, tag="12")]
    pub limit_processed_blocks: u64,
    #[prost(string, repeated, tag="13")]
    pub dev_output_modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag="14")]
    pub progress_messages_interval_ms: u64,
    #[prost(bool, tag="16")]
    pub partial_blocks: bool,
}
// @@protoc_insertion_point(module)
