// Bindings generated by build.rs (substreams_ethereum::Abigen) from abi/vault.json into OUT_DIR.
#[allow(dead_code, clippy::all)]
pub mod vault {
    include!(concat!(env!("OUT_DIR"), "/vault_abi.rs"));
}
