// Writes the generated MCP server package. Everything under --out is overwritten on each run except
// node_modules. Output is deterministic for identical inputs (no timestamps, no absolute paths).
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Manifest, ParamSpec, ToolSpec } from "../runtime/types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
export const RUNTIME_DIR = resolve(HERE, "..", "runtime");

export interface EmitOptions {
  outDir: string;
  packageName: string;
  manifest: Manifest;
  receiptJsonText: string;
  sdkVersionRange: string;
  zodVersionRange: string;
}

export interface EmitResult {
  manifestPath: string;
  files: string[];
}

const HEADER = "// GENERATED by @ethonline26/mcpgen. Do not edit: regenerate from the receipt, the proto and views.sql.\n";

function zodForParam(p: ParamSpec): string {
  const d = JSON.stringify(p.description);
  switch (p.kind) {
    case "vault":
      return `z.enum(VAULTS).optional().describe(${d})`;
    case "enumFilter":
      return `z.enum(${JSON.stringify(p.values ?? [])}).optional().describe(${d})`;
    case "windowHours": {
      const base = `z.number().int().min(${p.min ?? 1}).max(${p.max ?? 1})`;
      return p.optional ? `${base}.optional().describe(${d})` : `${base}.default(${p.default ?? 24}).describe(${d})`;
    }
    case "limit":
      return `z.number().int().min(${p.min ?? 1}).max(${p.max ?? 500}).default(${p.default ?? 100}).describe(${d})`;
  }
}

export function renderToolsModule(manifest: Manifest): string {
  const lines: string[] = [HEADER];
  lines.push(`import { z } from "zod";`);
  lines.push(`import type { ToolSpec } from "./runtime/types.ts";`);
  lines.push("");
  lines.push(`/** Vaults pinned by the Deployment Receipt (parameters.vaults, ${manifest.receipt.parametersHash.slice(0, 12)}...). The vault filter accepts nothing else. */`);
  lines.push(`export const VAULTS = ${JSON.stringify(manifest.vaults)} as const;`);
  lines.push(`export type Vault = (typeof VAULTS)[number];`);
  lines.push("");
  lines.push(`/** zod input shapes, one per tool. Closed sets: vault (receipt), direction (proto enum), integer bounds from the policy. */`);
  lines.push(`export const inputShapes = {`);
  for (const t of manifest.tools) {
    lines.push(`  ${t.name}: {`);
    for (const p of t.params) lines.push(`    ${p.name}: ${zodForParam(p)},`);
    lines.push(`  },`);
  }
  lines.push(`} satisfies Record<string, Record<string, z.ZodType>>;`);
  lines.push("");
  lines.push(`export type ToolName = keyof typeof inputShapes;`);
  lines.push("");
  lines.push(`/** Same content as manifest.json "tools"; embedded so the server has typed access without a JSON import. */`);
  lines.push(`export const TOOLS: readonly ToolSpec[] = ${JSON.stringify(manifest.tools, null, 2)};`);
  lines.push("");
  return lines.join("\n");
}

export function renderServer(manifest: Manifest, packageName: string): string {
  return `${HEADER}// MCP server for Substreams package ${manifest.package.name} ${manifest.package.version} (output module ${manifest.package.outputModule}).
// Transport: stdio. Configuration by environment:
//   CLICKHOUSE_URL        http(s)://host:port  (user:password@ and ?database= in the URL are honoured; default http://localhost:8123)
//   CLICKHOUSE_USER / CLICKHOUSE_PASSWORD / CLICKHOUSE_DATABASE
//   BASE_RPC_URL          JSON-RPC endpoint for the receipt's chain (eth_blockNumber / eth_chainId); required for the lag check
//   MAX_LAG_BLOCKS        refuse when chain head - sink head exceeds this (default ${manifest.policy.maxLagBlocksDefault})
//   CHECK_INTERVAL_SECONDS  fail-closed re-check period (default ${manifest.policy.checkIntervalSeconds})
//   RECEIPT_PATH          Deployment Receipt to re-read every cycle (default ./receipt.json next to manifest.json)
//   CLICKHOUSE_READONLY   1 (default) or 2; see runtime/clickhouse.ts
import { readFile, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { HttpClickHouseClient } from "./runtime/clickhouse.ts";
import { Guardian } from "./runtime/guardian.ts";
import { JsonRpcChainHead } from "./runtime/rpc.ts";
import { registerTools } from "./runtime/tools.ts";
import type { Manifest, RuntimeReceipt } from "./runtime/types.ts";
import { inputShapes } from "./tools.generated.ts";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const log = (m: string): void => { process.stderr.write(\`[${packageName}] \${m}\\n\`); };

const manifest = JSON.parse(readFileSync(join(pkgRoot, "manifest.json"), "utf8")) as Manifest;
const receiptPath = process.env.RECEIPT_PATH ?? join(pkgRoot, "receipt.json");
const readReceipt = (): Promise<RuntimeReceipt> =>
  new Promise((ok, fail) => readFile(receiptPath, "utf8", (err, text) => (err ? fail(err) : ok(JSON.parse(text) as RuntimeReceipt))));
const receiptAtStart = JSON.parse(readFileSync(receiptPath, "utf8")) as RuntimeReceipt;

const chUrl = new URL(process.env.CLICKHOUSE_URL ?? "http://localhost:8123");
const receiptSink = (receiptAtStart as { sink?: { database?: string } }).sink;
const database = process.env.CLICKHOUSE_DATABASE ?? chUrl.searchParams.get("database") ?? receiptSink?.database ?? "default";
const user = process.env.CLICKHOUSE_USER ?? (chUrl.username ? decodeURIComponent(chUrl.username) : undefined);
const password = process.env.CLICKHOUSE_PASSWORD ?? (chUrl.password ? decodeURIComponent(chUrl.password) : undefined);
const readonlyEnv = process.env.CLICKHOUSE_READONLY;
const clickhouse = new HttpClickHouseClient({
  url: \`\${chUrl.protocol}//\${chUrl.host}\`,
  ...(user !== undefined ? { user } : {}),
  ...(password !== undefined ? { password } : {}),
  database,
  timeoutMs: manifest.policy.queryTimeoutMs,
  readonly: readonlyEnv === "2" ? 2 : 1,
});

const rpcUrl = process.env.BASE_RPC_URL;
if (!rpcUrl) log("BASE_RPC_URL is not set: the lag check cannot run, so every data tool will refuse with check_unavailable");
const chainHead = rpcUrl
  ? new JsonRpcChainHead(rpcUrl, manifest.policy.queryTimeoutMs)
  : { head: async (): Promise<{ blockNumber: number; chainId: number }> => { throw new Error("BASE_RPC_URL not set"); } };

const maxLagBlocks = Number(process.env.MAX_LAG_BLOCKS ?? manifest.policy.maxLagBlocksDefault);
const checkIntervalMs = Number(process.env.CHECK_INTERVAL_SECONDS ?? manifest.policy.checkIntervalSeconds) * 1000;

const guardian = new Guardian({ manifest, readReceipt, clickhouse, chainHead, database, maxLagBlocks, checkIntervalMs, log });
const server = new McpServer({ name: ${JSON.stringify(packageName)}, version: ${JSON.stringify(manifest.package.version.replace(/^v/, ""))} });
registerTools(server, { guardian, clickhouse, log }, inputShapes);

const transport = new StdioServerTransport();
await server.connect(transport);
log(\`connected; \${manifest.tools.length} tools; package \${manifest.package.name} \${manifest.package.version} (\${manifest.package.deploymentMode}); database \${database}; maxLagBlocks \${maxLagBlocks}\`);
void guardian.start();
process.on("SIGINT", () => { guardian.stop(); process.exit(0); });
process.on("SIGTERM", () => { guardian.stop(); process.exit(0); });
`;
}

function renderPackageJson(o: EmitOptions): string {
  const bin = o.packageName.replace(/^@[^/]+\//, "");
  return JSON.stringify({
    name: o.packageName,
    version: o.manifest.package.version.replace(/^v/, ""),
    private: true,
    description: `Generated MCP server over the ${o.manifest.package.name} Substreams sink (fail-closed against Deployment Receipt ${o.manifest.receipt.sha256.slice(0, 12)}).`,
    type: "module",
    engines: { node: ">=22.18" },
    bin: { [bin]: "./bin/server.js" },
    scripts: {
      start: "node bin/server.js",
      typecheck: "tsc --noEmit",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": o.sdkVersionRange,
      zod: o.zodVersionRange,
    },
    devDependencies: {
      "@types/node": "^24.0.0",
      typescript: "^5.9.0",
    },
  }, null, 2) + "\n";
}

const TSCONFIG = JSON.stringify({
  compilerOptions: {
    target: "ES2022",
    module: "NodeNext",
    moduleResolution: "NodeNext",
    lib: ["ES2022", "DOM"],
    types: ["node"],
    strict: true,
    noUncheckedIndexedAccess: true,
    verbatimModuleSyntax: true,
    erasableSyntaxOnly: true,
    esModuleInterop: true,
    skipLibCheck: true,
    noEmit: true,
    allowImportingTsExtensions: true,
    resolveJsonModule: true,
  },
  include: ["src/**/*.ts"],
}, null, 2) + "\n";

const BIN = `#!/usr/bin/env node
// Runs the TypeScript server directly with Node's built-in type stripping (Node >= 22.18 / 23.6).
const [major, minor] = process.versions.node.split(".").map(Number);
if (major < 22 || (major === 22 && minor < 18)) {
  process.stderr.write("this server needs Node >= 22.18 (native TypeScript type stripping)\\n");
  process.exit(1);
}
await import("../src/server.ts");
`;

function paramTable(t: ToolSpec): string {
  if (t.params.length === 0) return "_no arguments_";
  const rows = t.params.map((p) => {
    let type: string;
    switch (p.kind) {
      case "vault": type = `enum of ${p.values?.length ?? 0} receipt vault(s), optional`; break;
      case "enumFilter": type = `enum ${(p.values ?? []).join(" | ")}, optional`; break;
      case "windowHours": type = `integer ${p.min}..${p.max}${p.optional ? ", optional (omit = whole observed window)" : `, default ${p.default}`}`; break;
      case "limit": type = `integer ${p.min}..${p.max}, default ${p.default}`; break;
    }
    return `| \`${p.name}\` | ${type} | ${p.description} |`;
  });
  return ["| argument | type | meaning |", "|---|---|---|", ...rows].join("\n");
}

export function renderReadme(o: EmitOptions): string {
  const m = o.manifest;
  const bin = o.packageName.replace(/^@[^/]+\//, "");
  const toolSections = m.tools.map((t) => {
    const cols = t.columns.length ? "\n\nColumns: " + t.columns.map((c) => `\`${c.name}\` (${c.type})`).join(", ") + "." : "";
    const extra = t.whenEmpty ? `\n\nWhen \`${t.source}\` has no live rows the tool answers \`{ "unavailable": true, "reason": ${JSON.stringify(t.whenEmpty.reason)} }\` instead of an empty list.` : "";
    return `### \`${t.name}\` (${t.kind}${t.source ? `: \`${t.source}\`` : ""})\n\n${t.description}\n\n${paramTable(t)}${cols}${extra}`;
  }).join("\n\n");
  return `# ${o.packageName}

Generated by \`@ethonline26/mcpgen\` from the public proto contract, the Deployment Receipt and the ClickHouse views of
Substreams package **${m.package.name} ${m.package.version}** (output module \`${m.package.outputModule}\`, chain ${m.package.chainId} / ${m.package.network},
deployment mode \`${m.package.deploymentMode}\`). Do not edit by hand: regenerate.

Identity (from \`manifest.json\`): package hash \`${m.package.packageHash}\`, output module hash \`${m.package.outputModuleHash}\`,
parameters hash \`${m.receipt.parametersHash}\`, proto descriptor hash \`${m.receipt.protoDescriptorHash}\`,
sink schema hash \`${m.receipt.sinkSchemaHash}\`, column-set hash \`${m.expectedSchema.columnSetHash}\`.

## What makes this server refuse

The server is **fail-closed**: it only answers from a deployment it has just verified against the receipt. On startup and
every ${m.policy.checkIntervalSeconds} s it

1. re-reads the receipt (\`RECEIPT_PATH\`) and checks its \`packageHash\`, \`outputModuleHash\`, \`parametersHash\`,
   \`protoDescriptorHash\` and \`sinkSchemaHash\` still equal the ones this server was generated for -> otherwise \`receipt_mismatch\`;
2. reads \`system.columns\` for ${Object.keys(m.expectedSchema.tables).length} expected tables (${Object.keys(m.expectedSchema.tables).map((t) => `\`${t}\``).join(", ")}) and compares a normalized
   column-set hash with \`manifest.json\` -> otherwise \`schema_mismatch\` (with \`expected\` and \`actual\` column sets and a diff);
3. asks \`BASE_RPC_URL\` for \`eth_chainId\` / \`eth_blockNumber\` and ClickHouse for the sink head (\`max(_block_number_)\`);
   wrong chain -> \`chain_mismatch\`; \`chainHead - headBlock > MAX_LAG_BLOCKS\` (default ${m.policy.maxLagBlocksDefault}) -> \`stale_data\`;
4. if any of the above could not be evaluated (ClickHouse or RPC unreachable, receipt unreadable, or the last successful
   check is older than 3 intervals) -> \`check_unavailable\`.

A refusal is returned by every data tool as
\`{ "refused": true, "reason": "<reason>", "detail": "...", "expected": ..., "actual": ..., "checkedAt": "...", "provenance": {...} }\`
with \`isError: true\`. \`pipeline_status\` never refuses; it reports the verdict.

Every successful response carries \`provenance\`: \`packageHash\`, \`outputModuleHash\`, \`parametersHash\`, \`protoDescriptorHash\`,
\`sinkSchemaHash\`, \`schemaColumnSetHash\`, \`deploymentMode\`, \`deploymentId\`, \`chainId\`, \`headBlock\`, \`headTimestamp\`, \`chainHead\`,
\`lagBlocks\`, \`observedWindow\` and \`checkedAt\`. \`observedWindow\` is measured on the data, never on configuration: \`observedFromTimestamp\` /
\`observedToTimestamp\` are min/max of the window column over live rows, \`startTimestamp\` / \`endTimestamp\` are this query's bounds
(\`hours\` back from the newest row, or the whole observed window when \`hours\` is null).

SQL is read-only and parameterized: identifiers come from the manifest, values are bound as ClickHouse query parameters
(\`{name:Type}\` + \`param_name\`), \`readonly=1\`, \`max_execution_time\` and a ${m.policy.queryTimeoutMs / 1000} s client timeout on every request, \`LIMIT\` <= ${m.policy.maxLimit}.
Wide numerics (UInt256, Decimal) are returned as strings; 64-bit integers are quoted by ClickHouse's JSON output as well.

## Tools

${toolSections}

## Run

\`\`\`bash
pnpm install                      # from the workspace root
export CLICKHOUSE_URL=http://localhost:8123 CLICKHOUSE_USER=ro CLICKHOUSE_PASSWORD=ropass CLICKHOUSE_DATABASE=vaultflows
export BASE_RPC_URL=https://mainnet.base.org
node bin/server.js                # stdio MCP server (Node >= 22.18)
\`\`\`

### Claude Code

\`\`\`bash
claude mcp add ${bin} \\
  -e CLICKHOUSE_URL=http://localhost:8123 -e CLICKHOUSE_USER=ro -e CLICKHOUSE_PASSWORD=ropass -e CLICKHOUSE_DATABASE=vaultflows \\
  -e BASE_RPC_URL=https://mainnet.base.org \\
  -- node /ABSOLUTE/PATH/TO/${bin}/bin/server.js
\`\`\`

or in \`.mcp.json\`:

\`\`\`json
{
  "mcpServers": {
    "${bin}": {
      "command": "node",
      "args": ["/ABSOLUTE/PATH/TO/${bin}/bin/server.js"],
      "env": {
        "CLICKHOUSE_URL": "http://localhost:8123",
        "CLICKHOUSE_USER": "ro",
        "CLICKHOUSE_PASSWORD": "ropass",
        "CLICKHOUSE_DATABASE": "vaultflows",
        "BASE_RPC_URL": "https://mainnet.base.org"
      }
    }
  }
}
\`\`\`

### Claude Desktop (\`claude_desktop_config.json\`)

\`\`\`json
{
  "mcpServers": {
    "${bin}": {
      "command": "node",
      "args": ["/ABSOLUTE/PATH/TO/${bin}/bin/server.js"],
      "env": {
        "CLICKHOUSE_URL": "http://localhost:8123",
        "CLICKHOUSE_USER": "ro",
        "CLICKHOUSE_PASSWORD": "ropass",
        "CLICKHOUSE_DATABASE": "vaultflows",
        "BASE_RPC_URL": "https://mainnet.base.org"
      }
    }
  }
}
\`\`\`

## Files

- \`manifest.json\` — tools, argument schemas, expected column sets, hashes (its sha256 goes into the receipt as \`mcpManifestHash\`).
- \`receipt.json\` — copy of the Deployment Receipt the server was generated from; re-read every cycle.
- \`src/tools.generated.ts\` — zod input shapes and tool specs; \`src/server.ts\` — entry point; \`src/runtime/\` — fail-closed guardian, SQL builder, ClickHouse and RPC clients.
`;
}

export async function emitPackage(o: EmitOptions): Promise<EmitResult> {
  const out = resolve(o.outDir);
  await mkdir(join(out, "src", "runtime"), { recursive: true });
  await mkdir(join(out, "bin"), { recursive: true });
  const files: string[] = [];
  const write = async (rel: string, content: string): Promise<void> => {
    const p = join(out, rel);
    await writeFile(p, content, "utf8");
    files.push(p);
  };
  for (const f of (await readdir(RUNTIME_DIR)).filter((f) => f.endsWith(".ts")).sort()) {
    await write(join("src", "runtime", f), await readFile(join(RUNTIME_DIR, f), "utf8"));
  }
  await write(join("src", "tools.generated.ts"), renderToolsModule(o.manifest));
  await write(join("src", "server.ts"), renderServer(o.manifest, o.packageName));
  await write(join("bin", "server.js"), BIN);
  await write("package.json", renderPackageJson(o));
  await write("tsconfig.json", TSCONFIG);
  await write("README.md", renderReadme(o));
  await write("receipt.json", o.receiptJsonText.endsWith("\n") ? o.receiptJsonText : o.receiptJsonText + "\n");
  const manifestPath = join(out, "manifest.json");
  await writeFile(manifestPath, JSON.stringify(o.manifest, null, 2) + "\n", "utf8");
  files.push(manifestPath);
  return { manifestPath, files };
}
