// Public import surface (the MCP generator imports from "./receipt" directly; everything else is here).
export * from "./receipt.ts";
export { runGate, runCommandArgv, templateVars, runOutputPath, moduleHashesOf, LIMIT_PROCESSED_BLOCKS_FLAG, type GateReport, type GateOutcome, type GateOptions, type GateRunReport } from "./gate/run.ts";
export { decodeRun, decodeRunFile, parseEnvelopes, camelToSnake, callStatus, foldLegacyCallStatus, TABLES, type ParsedRun, type Row } from "./gate/jsonl.ts";
export { ContractSchema, DecodeError } from "./gate/contract.ts";
export { evaluateAssertions, exitStatus, EVALUATORS, canonicalRunHash, decimalToScaled, type AssertionResult, type AssertionInputs, type DescriptorEvidence } from "./gate/assertions.ts";
export { gatherRpcEvidence, rpcNeeds, convertToAssetsCalldata, type RpcEvidence } from "./gate/rpc.ts";
export { loadGateConfig, parseGateConfig, expandTemplate, type GateConfig, type AssertionSpec, type GateRunSpec, DEFAULT_EXIT_CODES } from "./config/gate.ts";
export { loadStreamsmithConfig, type StreamsmithConfig } from "./config/streamsmith.ts";
export { specDescriptor, spkgDescriptor, normalizedDescriptorHash, makeContractWorkspace, substreamsInfo, protoPackageOf, type FdsJson, type DescriptorResult, type SubstreamsInfo } from "./proto/descriptor.ts";
export { runPublish, registryUrls, type PublishRecord } from "./publish.ts";
export { deployHosted, hostedStatus, portalLogin, AwaitingSecretError, EXIT_AWAITING_SECRET } from "./deploy/hosted.ts";
export { startSelfManaged, selfManagedStatus, stopSelfManaged, buildSinkCommand, parseDsn } from "./deploy/selfManaged.ts";
export { PortalClient, field as portalField } from "./deploy/portal.ts";
export { chQuery, chMaxBlock, chDumpSchema, schemaHash, clickhouseHttpUrl, clickhouseDatabase } from "./deploy/clickhouse.ts";
export { applyViews, splitSqlStatements, chTablesPresent, chViewNames, DEFAULT_VIEWS_PATH, type ViewsRecord } from "./deploy/views.ts";
export { ethBlockNumber } from "./deploy/rpc.ts";
export type { DeployRecord } from "./deploy/types.ts";
export { runMcp, mcpgenArgs, parseManifestLine, type McpRecord } from "./mcp.ts";
export { manifestStart, manifestFinish, type RunManifest } from "./manifest.ts";
export { renderCaseStudy, writeCaseStudy, type CaseStudyInput } from "./casestudy.ts";
export { createCtx, paths, type Ctx } from "./util/ctx.ts";
export { ProcessRunner, FakeRunner, type Runner, type RunResult, type FakeRule } from "./util/exec.ts";
export { sha256Hex, sha256File, canonicalJson, sha256Canonical } from "./util/hash.ts";
export { validateAgainstSchema } from "./schema/jsonschema.ts";
