//! erc4626-flows: ERC-4626 Deposit/Withdraw flows and sampled share-value observations on Base,
//! emitted as `vaultflows.v1.Events` for the ClickHouse from-proto sink.
//!
//! Module graph (see substreams.yaml):
//!   erc4626:map_events ─► store_vault_seen ─deltas─► map_vault_probe ─► store_vault_meta ─get─► map_flows ─┐
//!   Clock + params ─► map_share_value_observations ────────────────────────────────────────────────────────┼─► map_events
//!   map_vault_probe (first-sight VaultMeta rows) ─────────────────────────────────────────────────────────┘
//!
//! Contract rules honoured here (proto/vaultflows.proto header): numeric strings are never empty ("0" when not
//! computable, with `meta_valid` / `call_ok` telling the consumer to ignore them); ids are deterministic.

mod abi;
mod probe;
pub mod pure;

/// Protobuf bindings generated by `substreams protogen` (buf + neoeinstein-prost) into `src/pb/`.
/// Only the two packages this crate uses are wired in; the generated `src/pb/mod.rs` is not referenced.
pub mod pb {
    pub mod erc4626 {
        pub mod v1 {
            include!("pb/erc4626.v1.rs");
        }
    }
    pub mod vaultflows {
        pub mod v1 {
            include!("pb/vaultflows.v1.rs");
        }
    }
}

use pb::erc4626::v1 as erc4626;
use pb::vaultflows::v1::{Events, FlowDirection, ShareValueObservation, VaultFlow, VaultMeta};
use pure::{
    address_bytes, bytes_to_hex, execution_rate, flow_id, is_sample_block, normalize_amount, normalize_hash,
    normalize_rate, observation_id, or_zero, parse_params, vault_id, ZERO,
};
use substreams::errors::Error;
use substreams::pb::substreams::store_delta::Operation;
use substreams::pb::substreams::Clock;
use substreams::store::{
    DeltaInt64, Deltas, StoreGet, StoreGetProto, StoreNew, StoreSetIfNotExists, StoreSetIfNotExistsInt64,
    StoreSetIfNotExistsProto,
};

fn clock_seconds(clock: &Clock) -> u64 {
    clock
        .timestamp
        .as_ref()
        .map(|t| if t.seconds < 0 { 0 } else { t.seconds as u64 })
        .unwrap_or(0)
}

/// Every address that emitted a Deposit/Withdraw, keyed by lowercase 0x address. `set_if_not_exists`
/// makes the CREATE delta of this store a one-shot "first sight" signal per vault.
#[substreams::handlers::store]
fn store_vault_seen(events: erc4626::Events, store: StoreSetIfNotExistsInt64) {
    for trx in &events.transactions {
        for log in &trx.logs {
            if log.log.is_none() {
                continue;
            }
            store.set_if_not_exists(log.ordinal, bytes_to_hex(&log.address), &1i64);
        }
    }
}

/// First-sight metadata probe. One VaultMeta row per newly seen vault; `compliant=false` when any required
/// call failed. Only `Events.vaults` is populated.
#[substreams::handlers::map]
fn map_vault_probe(params: String, clock: Clock, deltas: Deltas<DeltaInt64>) -> Result<Events, Error> {
    let params = parse_params(&params).map_err(Error::msg)?;
    let mut out = Events::default();

    for delta in deltas.iter() {
        if delta.operation != Operation::Create {
            continue;
        }
        let vault = delta.key.as_str();
        let vault_bytes = match address_bytes(vault) {
            Ok(b) => b,
            Err(e) => {
                substreams::log::info!("skipping store key that is not an address: {}", e);
                continue;
            }
        };
        let probed = probe::probe_vault(&vault_bytes);
        substreams::log::info!(
            "first sight vault={} block={} compliant={} errors={:?}",
            vault,
            clock.number,
            probed.compliant(),
            probed.errors
        );
        out.vaults.push(VaultMeta {
            id: vault_id(params.chain_id, vault),
            chain_id: params.chain_id,
            vault: vault.to_string(),
            first_seen_block: clock.number,
            asset: probed.asset.clone(),
            asset_decimals: probed.asset_decimals.unwrap_or(0),
            share_decimals: probed.share_decimals.unwrap_or(0),
            name: probed.name.clone(),
            symbol: probed.symbol.clone(),
            compliant: probed.compliant(),
            in_configured_list: params.is_configured(vault),
            call_ok: probed.compliant(),
            call_error: probed.error_string(),
        });
    }
    Ok(out)
}

/// Cache of the probe result per vault. Written once, ever (set_if_not_exists).
#[substreams::handlers::store]
fn store_vault_meta(probed: Events, store: StoreSetIfNotExistsProto<VaultMeta>) {
    for meta in &probed.vaults {
        store.set_if_not_exists(0, &meta.vault, meta);
    }
}

/// One VaultFlow per Deposit/Withdraw on a configured vault. Only `Events.vault_flows` is populated.
#[substreams::handlers::map]
fn map_flows(
    params: String,
    clock: Clock,
    events: erc4626::Events,
    meta_store: StoreGetProto<VaultMeta>,
) -> Result<Events, Error> {
    let params = parse_params(&params).map_err(Error::msg)?;
    let block_hash = normalize_hash(&clock.id);
    let block_timestamp = clock_seconds(&clock);
    let mut out = Events::default();

    for trx in &events.transactions {
        let tx_hash = bytes_to_hex(&trx.hash);
        for log in &trx.logs {
            let vault = bytes_to_hex(&log.address);
            if !params.is_configured(&vault) {
                continue;
            }
            let (direction, caller, owner, receiver, assets_raw, shares_raw) = match &log.log {
                Some(erc4626::log::Log::Deposit(d)) => (
                    FlowDirection::Deposit,
                    bytes_to_hex(&d.sender),
                    bytes_to_hex(&d.owner),
                    // On deposit the shares go to `owner`; the contract defines receiver == owner here.
                    bytes_to_hex(&d.owner),
                    or_zero(&d.assets),
                    or_zero(&d.shares),
                ),
                Some(erc4626::log::Log::Withdraw(w)) => (
                    FlowDirection::Withdraw,
                    bytes_to_hex(&w.sender),
                    bytes_to_hex(&w.owner),
                    bytes_to_hex(&w.receiver),
                    or_zero(&w.assets),
                    or_zero(&w.shares),
                ),
                None => continue,
            };

            let (meta_valid, asset_decimals, share_decimals, call_ok, call_error) = match meta_store.get_last(&vault) {
                Some(m) if m.compliant => (true, m.asset_decimals, m.share_decimals, m.call_ok, m.call_error.clone()),
                Some(m) => {
                    // Non-compliant addresses never produce VaultFlow rows (contract: VaultMeta doc).
                    substreams::log::info!(
                        "dropping flow on non-compliant vault={} tx={} reason={:?}",
                        vault,
                        tx_hash,
                        m.call_error
                    );
                    continue;
                }
                None => (false, 0, 0, false, "meta: not available at this block".to_string()),
            };

            let (assets_normalized, shares_normalized, rate) = if meta_valid {
                (
                    normalize_amount(&assets_raw, asset_decimals).unwrap_or_else(|| ZERO.to_string()),
                    normalize_amount(&shares_raw, share_decimals).unwrap_or_else(|| ZERO.to_string()),
                    execution_rate(&assets_raw, asset_decimals, &shares_raw, share_decimals)
                        .unwrap_or_else(|| ZERO.to_string()),
                )
            } else {
                (ZERO.to_string(), ZERO.to_string(), ZERO.to_string())
            };

            out.vault_flows.push(VaultFlow {
                id: flow_id(params.chain_id, clock.number, log.block_index),
                chain_id: params.chain_id,
                block_number: clock.number,
                block_hash: block_hash.clone(),
                block_timestamp,
                tx_hash: tx_hash.clone(),
                log_index: log.block_index,
                vault,
                caller,
                owner,
                receiver,
                direction: direction as i32,
                assets_raw,
                shares_raw,
                assets_normalized,
                shares_normalized,
                asset_decimals,
                share_decimals,
                execution_rate: rate,
                meta_valid,
                call_ok,
                call_error,
            });
        }
    }
    Ok(out)
}

/// Sampled point-in-time reads for every configured vault when `block_number % interval == 0`.
/// Only `Events.share_value_observations` is populated; on other blocks the output is empty.
#[substreams::handlers::map]
fn map_share_value_observations(params: String, clock: Clock) -> Result<Events, Error> {
    let params = parse_params(&params).map_err(Error::msg)?;
    let mut out = Events::default();
    if !is_sample_block(clock.number, params.interval) {
        return Ok(out);
    }

    let vault_bytes = params
        .vaults
        .iter()
        .map(|v| address_bytes(v))
        .collect::<Result<Vec<_>, _>>()
        .map_err(Error::msg)?;
    let observed = probe::observe_vaults(&vault_bytes);
    let block_hash = normalize_hash(&clock.id);
    let block_timestamp = clock_seconds(&clock);

    for (vault, obs) in params.vaults.iter().zip(observed.into_iter()) {
        let assets_per_share_normalized = match (&obs.assets_per_share, obs.asset_decimals) {
            (Some(raw), Some(dec)) => normalize_rate(raw, dec).unwrap_or_else(|| ZERO.to_string()),
            _ => ZERO.to_string(),
        };
        substreams::log::info!(
            "observation block={} vault={} ok={} errors={:?}",
            clock.number,
            vault,
            obs.ok(),
            obs.errors
        );
        out.share_value_observations.push(ShareValueObservation {
            id: observation_id(params.chain_id, clock.number, vault),
            chain_id: params.chain_id,
            block_number: clock.number,
            block_hash: block_hash.clone(),
            block_timestamp,
            vault: vault.clone(),
            sample_interval_blocks: params.interval.min(u32::MAX as u64) as u32,
            assets_per_share_raw: obs.assets_per_share.clone().unwrap_or_else(|| ZERO.to_string()),
            assets_per_share_normalized,
            total_assets_raw: obs.total_assets.clone().unwrap_or_else(|| ZERO.to_string()),
            total_supply_raw: obs.total_supply.clone().unwrap_or_else(|| ZERO.to_string()),
            call_ok: obs.ok(),
            call_error: obs.error_string(),
        });
    }
    Ok(out)
}

/// The single sink module: merges flows, observations and first-sight VaultMeta rows.
#[substreams::handlers::map]
fn map_events(flows: Events, observations: Events, probed: Events) -> Result<Events, Error> {
    Ok(Events {
        vault_flows: flows.vault_flows,
        share_value_observations: observations.share_value_observations,
        vaults: probed.vaults,
        share_transfers: Vec::new(),
    })
}
